
export const championship = [
  {
    id: "copa-adc-2026",
    name: "Copa ADC Renuka",
    season: "2026",
    current: true,
    groups: [
        {
    name: "Grupo A",
    teams: [
      { name: "Águias de Deus", short: "ADS", logo: "/times/aguias_de_Deus.png", },
      { name: "Max Elite", short: "MXE", logo: "/times/maxelite.png", },
      { name: "MEC", short: "MEC", logo: "/times/mec.png", },
      { name: "A Firma", short: "AFA", logo: "/times/afirma.png", },
    ],
    matches: [
      { home: "ADS", away: "MXE", date: "12/04", time: "08:00", homeScore: 4, awayScore: 3 },
      { home: "MEC", away: "AFA", date: "12/04", time: "08:00", homeScore: 4, awayScore: 2 },
      { home: "MEC", away: "MXE", date: "26/04", time: "08:00", homeScore: 2, awayScore: 0 },
      { home: "AFA", away: "ADS", date: "26/04", time: "09:10", homeScore: 3, awayScore: 1 },
      { home: "AFA", away: "MXE", date: "17/05", time: "08:00", },
      { home: "MEC", away: "ADS", date: "17/05", time: "09:10", },
    ],
  },
  {
    name: "Grupo B",
    teams: [
      { name: "ADC Renuka", short: "ADC", logo: "/times/renukaadc.png", },
      { name: "Napoli", short: "NPI", logo: "/times/napoli.png", },
      { name: "Casinha FC", short: "CFC", logo: "/times/casinhafc.png", },
      { name: "União São João", short: "USJ", logo: "/times/unidos_sao_joao.png", },
    ],
    matches: [
      { home: "ADC", away: "NPI", date: "12/04", time: "08:00", homeScore: 1, awayScore: 3 },
      { home: "CFC", away: "USJ", date: "12/04", time: "08:00", homeScore: 3, awayScore: 2 },
      { home: "USJ", away: "ADC", date: "26/04", time: "08:00", homeScore: 3, awayScore: 0 },
      { home: "NPI", away: "CFC", date: "26/04", time: "09:10", homeScore: 3, awayScore: 4 },
      { home: "CFC", away: "ADC", date: "17/05", time: "08:00", },
      { home: "USJ", away: "NPI", date: "17/05", time: "09:10", },
    ],
  },
  {
    name: "Grupo C",
    teams: [
      { name: "Boleiros", short: "BLS", logo: "/times/boleirosfc.png", },
      { name: "Os Paraíbas", short: "PRB", logo: "/times/os_paraibas.png", },
      { name: "Nova Aliança", short: "NAL", logo: "/times/nova_alianca.png", },
      { name: "Point", short: "PIT", logo: "/times/point.png", },
    ],
    matches: [
      { home: "BLS", away: "PRB", date: "19/04", time: "08:00", homeScore: 1, awayScore: 5 },
      { home: "NAL", away: "PIT", date: "19/04", time: "08:00", homeScore: 2, awayScore: 2 },
      { home: "PRB", away: "NAL", date: "03/05", time: "08:00", },
      { home: "PIT", away: "BLS", date: "03/05", time: "09:10", },
      { home: "PIT", away: "PRB", date: "24/05", time: "08:00", },
      { home: "NAL", away: "BLS", date: "24/05", time: "09:10", },
    ],
  },
  {
    name: "Grupo D",
    teams: [
      { name: "Magos FC", short: "MAG", logo: "/times/magos.png", },
      { name: "Sporting Guaiçara", short: "SGC", logo: "/times/sporting-guaicarafc.png", },
      { name: "The Best", short: "TBT", logo: "/times/the_best.png", },
      { name: "Raiz Esportiva", short: "RZS", logo: "/times/raizesportiva.png", },
    ],
    matches: [
      { home: "MAG", away: "RZS", date: "19/04", time: "08:00", homeScore: 15, awayScore: 1 },
      { home: "TBT", away: "SGC", date: "19/04", time: "08:00", homeScore: 2, awayScore: 4 },
      { home: "RZS", away: "TBT", date: "03/05", time: "08:00", },
      { home: "SGC", away: "MAG", date: "03/05", time: "09:10", },
      { home: "SGC", away: "RZS", date: "24/05", time: "08:00", },
      { home: "TBT", away: "MAG", date: "24/05", time: "09:10", },
    ]
      }
    ]
  },
 {
    id: "copa-selt40-2026",
    name: "Copa Selt Promissão 40",
    season: "2026",
    current: true,
    groups: [
        {
    name: "Grupo A",
    teams: [
      { name: "Bengala", short: "BGA", logo: "/times/bengala.png", },
      { name: "Bahea", short: "BAE", logo: "/times/bahea.png", },
      { name: "Falcões", short: "FAC", logo: "/times/falcoes.png", },
      { name: "Mec", short: "MEC", logo: "/times/mec.png", },
      { name: "Bem Amigos", short: "BAG", logo: "/times/bemamigosfc.png", },
    ],
    matches: [
      { home: "BGA", away: "BAE", date: "25/04", time: "17:45", homeScore: 0, awayScore: 4 },
      { home: "FAC", away: "BAG", date: "25/04", time: "17:45", homeScore: 13, awayScore: 1 },
      { home: "MEC", away: "FAC", date: "05/05", time: "19:00", },
      { home: "BAG", away: "BGA", date: "05/05", time: "19:00", },
      { home: "BAE", away: "BAG", date: "09/05", time: "19:30", },
      { home: "BGA", away: "MEC", date: "09/05", time: "19:30", },
      { home: "FAC", away: "BGA", date: "14/05", time: "21:00", },
      { home: "MEC", away: "BAE", date: "14/05", time: "21:00", },
      { home: "BAG", away: "MEC", date: "19/05", time: "19:00", },
      { home: "BAE", away: "FAC", date: "19/05", time: "19:00", },
    ],
  },
  {
    name: "Grupo B",
    teams: [
      { name: "Assentamento", short: "ASS", logo: "/times/assentamento50.png", },
      { name: "Promi Informatica", short: "PRO", logo: "/times/promi_informatica.png", },
      { name: "Grupo Deu Bom", short: "GDB", logo: "/times/grupodeubom.png", },
      { name: "Amigos do Futebol", short: "ADF", logo: "/times/amigosdofutebol50.png", },
    ],
    matches: [
      { home: "ASS", away: "ADF", date: "25/04", time: "18:30", homeScore: 5, awayScore: 2 },
      { home: "GDB", away: "PRO", date: "25/04", time: "18:30", homeScore: 3, awayScore: 1 },
      { home: "GDB", away: "ASS", date: "05/05", time: "20:00", },
      { home: "PRO", away: "ADF", date: "05/05", time: "20:00", },
      { home: "ASS", away: "PRO", date: "09/05", time: "18:30", },
      { home: "ADF", away: "GDB", date: "09/05", time: "18:30", },
    ]
      }
    ]
  },
  {
    id: "copa-selt-livre-2026",
    name: "Copa Selt Promissão Livre",
    season: "2026",
    current: true,
    groups: [
              {
          name: "Grupo A",
          teams: [
            { name: "Nova Campinas FC", short: "NCF", logo: "/times/novacampinas.png", },
            { name: "Aliança FC", short: "AFC", logo: "/times/aliancafc.png", },
            { name: "Point FC", short: "PIT", logo: "/times/point.png", },
            { name: "The Best", short: "TBT", logo: "/times/the_best.png", },
            { name: "Beco FC", short: "BEC", logo: "/times/becofc.png", },
            { name: "Bahea", short: "BAE", logo: "/times/bahea.png", },
          ],
          matches: [
            { home: "BAE", away: "PIT", date: "23/04", time: "19:00", homeScore: 2, awayScore: 4 },
            { home: "AFC", away: "BEC", date: "23/04", time: "19:00", homeScore: 1, awayScore: 19 },
            { home: "NCF", away: "TBT", date: "28/04", time: "20:00", homeScore: 4, awayScore: 1 },
            { home: "AFC", away: "BAE", date: "28/04", time: "20:00", homeScore: 0, awayScore: 15},
            { home: "TBT", away: "PIT", date: "05/05", time: "21:00", },
            { home: "BEC", away: "NCF", date: "05/05", time: "21:00", },
            { home: "BAE", away: "TBT", date: "12/05", time: "19:00", },
            { home: "NCF", away: "AFC", date: "12/05", time: "19:00", },
            { home: "BAE", away: "TBT", date: "16/05", time: "19:30", },
            { home: "NCF", away: "BAE", date: "16/05", time: "19:30", },
            { home: "BEC", away: "TBT", date: "21/05", time: "21:00", },
            { home: "AFC", away: "PIT", date: "21/05", time: "21:00", },
            { home: "BAE", away: "BEC", date: "26/05", time: "19:00", },
            { home: "PIT", away: "NCF", date: "21/05", time: "19:00", },
            { home: "TBT", away: "AFC", date: "30/05", time: "17:15", },
            
          ],
        },
        {
          name: "Grupo B",
          teams: [
            { name: "Bengala FC", short: "BGA", logo: "/times/bengala.png", },
            { name: "Águias de Deus", short: "ADF", logo: "/times/aguias_de_Deus.png", },
            { name: "Borussia", short: "BVB", logo: "/times/borussia.png", },
            { name: "São José", short: "SJC", logo: "/times/saojose.png", },
            { name: "Conexão FC", short: "CFC", logo: "/times/conexaofc.png", },
            { name: "Meninos da Vila", short: "MDV", logo: "/times/meninos_da_vila.png", },
          ],
          matches: [
            { home: "MDV", away: "SJC", date: "23/04", time: "20:00", homeScore: 6, awayScore: 4 },
            { home: "CFC", away: "BGA", date: "23/04", time: "20:00", homeScore: 0, awayScore: 11 },
            { home: "ADF", away: "BVB", date: "28/04", time: "21:00", homeScore: 1, awayScore: 1 },
            { home: "CFC", away: "MDV", date: "28/04", time: "21:00", homeScore: 0, awayScore: 13},
            { home: "BVB", away: "SJC", date: "07/05", time: "19:00", },
            { home: "BGA", away: "ADF", date: "07/05", time: "19:00", },
            { home: "MDV", away: "BVB", date: "12/05", time: "20:00", },
            { home: "ADF", away: "CFC", date: "12/05", time: "20:00", },
            { home: "SJC", away: "BGA", date: "16/05", time: "18:30", },
            { home: "ADF", away: "MDV", date: "16/05", time: "18:30", },
            { home: "BAG", away: "BVB", date: "21/05", time: "19:00", },
            { home: "CFC", away: "SJC", date: "21/05", time: "19:00", },
            { home: "MDV", away: "BGA", date: "26/05", time: "20:00", },
            { home: "SJC", away: "ADF", date: "26/05", time: "20:00", },
            { home: "BVB", away: "CFC", date: "30/05", time: "17:15", },
          ],
        },
        {
          name: "Grupo C",
          teams: [
            { name: "ADC Renuka", short: "ADC", logo: "/times/renukaadc.png", },
            { name: "Os Paraíbas", short: "PRB", logo: "/times/os_paraibas.png", },
            { name: "Promi Informática", short: "PRO", logo: "/times/promi_informatica.png", },
            { name: "BFC", short: "BFC", logo: "/times/bfc.png", },
            { name: "Real Central FC", short: "RCF", logo: "/times/realcentral.png", },
            { name: "Falcões", short: "FAL", logo: "/times/falcoes.png", },
          ],
          matches: [
            { home: "FAL", away: "ADC", date: "23/04", time: "21:00", homeScore: 7, awayScore: 1 },
            { home: "PRB", away: "BFC", date: "23/04", time: "21:00", homeScore: 5, awayScore: 1 },
            { home: "RCF", away: "PRO", date: "30/04", time: "19:00", homeScore: 2, awayScore: 0 },
            { home: "PRB", away: "FAL", date: "30/04", time: "19:00", homeScore: 2, awayScore: 4 },
            { home: "PRO", away: "ADC", date: "07/05", time: "20:00", },
            { home: "BFC", away: "RCF", date: "07/05", time: "20:00", },
            { home: "FAL", away: "PRO", date: "12/05", time: "21:00", },
            { home: "RCF", away: "PRB", date: "12/05", time: "21:00", },
            { home: "ADC", away: "BFC", date: "16/05", time: "17:15", },
            { home: "RCF", away: "FAL", date: "16/05", time: "17:15", },
            { home: "BFC", away: "PRO", date: "21/05", time: "20:00", },
            { home: "PRB", away: "ADC", date: "21/05", time: "20:00", },
            { home: "FAL", away: "BFC", date: "26/05", time: "21:00", },
            { home: "ADC", away: "RCF", date: "26/05", time: "21:00", },
            { home: "PRO", away: "PRB", date: "30/05", time: "18:30", },
          ],
        },
        {
          name: "Grupo D",
          teams: [
            { name: "Guerreiros FC", short: "GFC", logo: "/times/guerreirosfc.png", },
            { name: "MEC", short: "MEC", logo: "/times/mec.png", },
            { name: "Athletic", short: "ATL", logo: "/times/athleticfc.png", },
            { name: "Leões", short: "LEO", logo: "/times/leoesfc.png", },
            { name: "União São João", short: "USJ", logo: "/times/unidos_sao_joao.png", },
            { name: "Napoli", short: "NAP", logo: "/times/napoli.png", },
          ],
          matches: [
            { home: "NAP", away: "ATL", date: "25/04", time: "19:30", homeScore: 3, awayScore: 1},
            { home: "USJ", away: "GFC", date: "25/04", time: "19:30", homeScore: 3, awayScore: 0},
            { home: "MEC", away: "LEO", date: "30/04", time: "21:00", },
            { home: "USJ", away: "NAP", date: "30/04", time: "21:00", },
            { home: "LEO", away: "ATL", date: "07/05", time: "21:00", },
            { home: "GFC", away: "MEC", date: "07/05", time: "21:00", },
            { home: "NAP", away: "LEO", date: "14/05", time: "19:00", },
            { home: "MEC", away: "USJ", date: "14/05", time: "19:00", },
            { home: "ATL", away: "GFC", date: "19/05", time: "20:00", },
            { home: "MEC", away: "NAP", date: "19/05", time: "20:00", },
            { home: "GFC", away: "LEO", date: "23/05", time: "17:15", },
            { home: "USJ", away: "ATL", date: "23/05", time: "17:15", },
            { home: "NAP", away: "GFC", date: "28/05", time: "19:00", },
            { home: "ATL", away: "MEC", date: "28/05", time: "19:00", },
            { home: "LEO", away: "USJ", date: "30/05", time: "18:30", },
          ],
        },
    ]
  }
]
