// /app/api/jogos/route.ts

import { NextResponse } from "next/server"

const jogos = [
    {
      id: "1",
      homeLogo: "/times/bengala.png",
      home: "Bengala",
      awayLogo: "/times/bahea.png",
      away: "Bahea",
      score: "0 x 4",
      type: "Copa Mini campo Selt 40+",
      data: "2026-04-25",
      hora: "17:45",
      local: "Estádio Municipal",
    },
    {
      id: "2",
      homeLogo: "/times/falcoes.png",
      home: "Falcões",
      awayLogo: "/times/bemamigosfc.png",
      away: "Bem Amigos",
      score: "13 x 1",
      type: "Copa Mini campo Selt 40+",
      data: "2026-04-25",
      hora: "17:45",
      local: "Estádio Municipal",
    },
    {
      id: "3",
      homeLogo: "/times/assentamento50.png",
      home: "assentamento",
      awayLogo: "/times/amigos_do_futebol40.png",
      away: "Amigos do Futebol",
      score: "5 x 2",
      type: "Copa Mini campo Selt 40+",
      data: "2026-04-25",
      hora: "18:30",
      local: "Estádio Municipal",
    },
    {
      id: "4",
      homeLogo: "/times/grupodeubom.png",
      home: "Grupo Deu Bom",
      awayLogo: "/times/promi_informatica.png",
      away: "Promi informática",
      score: "3 x 1",
      type: "Copa Mini campo Selt 40+",
      data: "2026-04-25",
      hora: "18:30",
      local: "Estádio Municipal",
    },
    {
      id: "5",
      homeLogo: "/times/maxelite.png",
      home: "Max Elite",
      awayLogo: "/times/mec.png",
      away: "MEC",
      score: "0 x 2",
      type: "Copa ADC",
      data: "2026-04-26",
      hora: "08:00",
      local: "Arena ADC",
    },
    {
      id: "6",
      homeLogo: "/times/unidos_sao_joao.png",
      home: "São João",
      awayLogo: "/times/renukaadc.png",
      away: "ADC Renuka",
      score: "3 x 0",
      type: "Copa ADC",
      data: "2026-04-26",
      hora: "08:00",
      local: "Arena ADC",
    },
    {
      id: "7",
      homeLogo: "/times/afirma.png",
      home: "A Firma",
      awayLogo: "/times/aguias_de_Deus.png",
      away: "Águias de Deus",
      score: "3 x 1",
      type: "Copa ADC",
      data: "2026-04-26",
      hora: "09:10",
      local: "Arena ADC",
    },
    {
      id: "8",
      homeLogo: "/times/napoli.png",
      home: "Napoli",
      awayLogo: "/times/casinhafc.png",
      away: "Casinha FC",
      score: "3 x 4",
      type: "Copa ADC",
      data: "2026-04-26",
      hora: "09:10",
      local: "Arena ADC",
    },
    {
      id: "9",
      homeLogo: "/times/os_paraibas.png",
      home: "Os Paraibas",
      awayLogo: "/times/nova_alianca.png",
      away: "Nova Aliança",
      score: "7 x 4",
      type: "Copa ADC",
      data: "2026-05-03",
      hora: "08:00",
      local: "Arena ADC",
    },
    {
      id: "10",
      homeLogo: "/times/raizesportiva.png",
      home: "Raiz Esportiva",
      awayLogo: "/times/the_best.png",
      away: "The Best",
      score: "3 x 8",
      type: "Copa ADC",
      data: "2026-05-03",
      hora: "08:00",
      local: "Arena ADC",
    },
    {
      id: "11",
      homeLogo: "/times/point.png",
      home: "Point",
      awayLogo: "/times/boleirosfc.png",
      away: "Boleiros",
      score: "4 x 2",
      type: "Copa ADC",
      data: "2026-05-03",
      hora: "09:10",
      local: "Arena ADC",
    },
    {
      id: "12",
      homeLogo: "/times/sporting-guaicarafc.png",
      home: "Sporting Guaicara",
      awayLogo: "/times/magos.png",
      away: "Magos",
      score: "2 x 2",
      type: "Copa ADC",
      data: "2026-05-03",
      hora: "09:10",
      local: "Arena ADC",
    },
    {
      id: "13",
      homeLogo: "/times/nova_alianca.png",
      home: "Nova Aliança",
      awayLogo: "/times/point.png",
      away: "Point",
      score: "2 x 2",
      type: "Copa ADC",
      data: "2026-04-19",
      hora: "08:00",
      local: "Arena ADC - Campo A",
    },
    {
        id: "14",
      homeLogo: "/times/boleirosfc.png",
      home: "Boleiros",
      awayLogo: "/times/os_paraibas.png",
      away: "Os Paraíbas",
      score: "1 x 5",
      type: "Copa ADC",
      data: "2026-04-19",
      hora: "08:00",
      local: "Arena ADC - Campo A",
    },
    {
        id: "15",
      homeLogo: "/times/sporting-guaicarafc.png",
      home: "Sporting Guaiçara",
      awayLogo: "/times/the_best.png",
      away: "The Best",
      score: "4 x 2",
      type: "Copa ADC",
      data: "2026-04-19",
      hora: "08:00",
      local: "Arena ADC - Campo B",
    },
    {
        id: "16",
      homeLogo: "/times/magos.png",
      home: "Magos",
      awayLogo: "/times/raizesportiva.png",
      away: "Raiz Esportiva",
      score: "15 x 1",
      type: "Copa ADC",
      data: "2026-04-19",
      hora: "08:00",
      local: "Arena ADC - Campo B",
      
    },
  {
    id: "17",
      homeLogo: "/times/the_best.png",
      home: "The Best",
      awayLogo: "/times/os_paraibas.png",
      away: "Os Paraibas",
      score: "3 x 5",
      type: "Amistoso",
      data: "2026-04-12",
      hora: "08:30",
      local: "Campo São João"
    },
    {
        id: "18",
      homeLogo: "/times/casinhafc.png",
      home: "Casinha FC",
      awayLogo: "/times/unidos_sao_joao.png",
      away: "Unidos São João",
      score: "3 x 2",
      type: "Copa ADC",
      data: "2026-04-12",
      hora: "08:00",
      local: "Arena ADC - Campo B"
    },
    {
        id: "19",
      homeLogo: "/times/renukaadc.png",
      home: "Renuka ADC",
      awayLogo: "/times/napoli.png",
      away: "Napoli",
      score: "1 x 3",
      type: "Copa ADC",
      data: "2026-04-12",
      hora: "08:00",
      local: "Arena ADC - Campo B"
    },
    {
        id: "20",
      homeLogo: "/times/aguias_de_Deus.png",
      home: "Águias de Deus",
      awayLogo: "/times/maxelite.png",
      away: "Max Elite",
      score: "4 x 3",
      type: "Copa ADC",
      data: "2026-04-12",
      hora: "08:00",
      local: "Arena ADC - Campo A"
    },
    {
        id: "21",
      homeLogo: "/times/sporting-guaicarafc.png",
      home: "Sporting Guaiçara",
      awayLogo: "/times/bulldogs.png",
      away: "BullDogs",
      score: "9 x 4",
      type: "Amistoso",
      data: "2026-04-12",
      hora: "08:30",
      local: "Arena Travalão"
    },
    {
        id: "22",
      homeLogo: "/times/mec.png",
      home: "MEC",
      awayLogo: "/times/afirma.png",
      away: "Firma",
      score: "4 x 2",
      type: "Copa ADC",
      data: "2026-04-12",
      hora: "08:00",
      local: "Arena ADC - Campo A"
    },
    {
        id: "23",
      homeLogo: "/times/amigos_do_futebol40.png",
      home: "ADF",
      awayLogo: "/times/bengala.png",
      away: "BNG",
      score: "2 x 4",
      type: "Copa selt 50+",
      data: "2026-05-09",
      hora: "17:15",
      local: "Estádio verano Piromalli"
    },
    {
        id: "24",
      homeLogo: "/times/assentamento50.png",
      home: "ASS",
      awayLogo: "/times/arenamartinez50.png",
      away: "AMB",
      score: "2 x 5",
      type: "Copa selt 50+",
      data: "2026-05-09",
      hora: "17:15",
      local: "Estádio verano Piromalli"
    },
    {
        id: "25",
      homeLogo: "/times/mec.png",
      home: "MEC",
      awayLogo: "/times/falcoes.png",
      away: "FAC",
      score: "0 x 8",
      type: "Copa selt 40+",
      data: "2026-05-05",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "26",
      homeLogo: "/times/bemamigosfc.png",
      home: "BAG",
      awayLogo: "/times/bengala.png",
      away: "BGA",
      score: "0 x 8",
      type: "Copa selt 40+",
      data: "2026-05-05",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "27",
      homeLogo: "/times/grupodeubom.png",
      home: "GDB",
      awayLogo: "/times/assentamento50.png",
      away: "ASS",
      score: "0 x 5",
      type: "Copa selt 40+",
      data: "2026-05-05",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "28",
      homeLogo: "/times/promi_informatica.png",
      home: "PRO",
      awayLogo: "/times/amigosdofutebol50.png",
      away: "ADF",
      score: "1 x 1",
      type: "Copa selt 40+",
      data: "2026-05-05",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "29",
      homeLogo: "/times/the_best.png",
      home: "TBT",
      awayLogo: "/times/point.png",
      away: "PIT",
      score: "1 x 4",
      type: "Copa selt livre",
      data: "2026-05-05",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "30",
      homeLogo: "/times/becofc.png",
      home: "BEC",
      awayLogo: "/times/novacampinas.png",
      away: "NCF",
      score: "4 x 1",
      type: "Copa selt livre",
      data: "2026-05-05",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "31",
      homeLogo: "/times/borussia.png",
      home: "BVB",
      awayLogo: "/times/saojose.png",
      away: "sjc",
      score: "1 x 7",
      type: "Copa selt livre",
      data: "2026-05-07",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "32",
      homeLogo: "/times/bengala.png",
      home: "BGA",
      awayLogo: "/times/aguias_de_Deus.png",
      away: "ADD",
      score: "9 x 0",
      type: "Copa selt livre",
      data: "2026-05-07",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "33",
      homeLogo: "/times/promi_informatica.png",
      home: "PRO",
      awayLogo: "/times/renukaadc.png",
      away: "ADC",
      score: "0 x 4",
      type: "Copa selt livre",
      data: "2026-05-07",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "34",
      homeLogo: "/times/bfc.png",
      home: "BFC",
      awayLogo: "/times/realcentral.png",
      away: "RCF",
      score: "5 x 3",
      type: "Copa selt livre",
      data: "2026-05-07",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "35",
      homeLogo: "/times/leoesfc.png",
      home: "LEO",
      awayLogo: "/times/athleticfc.png",
      away: "ATL",
      score: "0 x 5",
      type: "Copa selt livre",
      data: "2026-05-07",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "36",
      homeLogo: "/times/guerreirosfc.png",
      home: "GFC",
      awayLogo: "/times/mec.png",
      away: "MEC",
      score: "1 x 2",
      type: "Copa selt livre",
      data: "2026-05-07",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "37",
      homeLogo: "/times/bahea.png",
      home: "BAE",
      awayLogo: "/times/bemamigosfc.png",
      away: "BAG",
      score: "5 x 2",
      type: "Copa selt 40+",
      data: "2026-05-09",
      hora: "19:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "38",
      homeLogo: "/times/bengala.png",
      home: "BGA",
      awayLogo: "/times/mec.png",
      away: "MEC",
      score: "2 x 0",
      type: "Copa selt 40+",
      data: "2026-05-09",
      hora: "19:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "39",
      homeLogo: "/times/assentamento50.png",
      home: "ASS",
      awayLogo: "/times/promi_informatica.png",
      away: "PRO",
      score: "3 x 2",
      type: "Copa selt 40+",
      data: "2026-05-09",
      hora: "18:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "40",
      homeLogo: "/times/amigos_do_futebol40.png",
      home: "ADF",
      awayLogo: "/times/grupodeubom.png",
      away: "GDB",
      score: "3 x 2",
      type: "Copa selt 40+",
      data: "2026-05-09",
      hora: "18:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "41",
      homeLogo: "/times/assentamento50.png",
      home: "ASS",
      awayLogo: "/times/amigos_do_futebol40.png",
      away: "ADF",
      score: "2 x 3",
      type: "Copa selt 50+",
      data: "2026-05-14",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "42",
      homeLogo: "/times/bengala.png",
      home: "BGA",
      awayLogo: "/times/arenamartinez50.png",
      away: "AMB",
      score: "0 x 0",
      type: "Copa selt 50+",
      data: "2026-05-14",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "43",
      homeLogo: "/times/falcoes.png",
      home: "FAC",
      awayLogo: "/times/bengala.png",
      away: "BGA",
      score: "1 x 0",
      type: "Copa selt 40+",
      data: "2026-05-14",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "44",
      homeLogo: "/times/mec.png",
      home: "MEC",
      awayLogo: "/times/bahea.png",
      away: "BAE",
      score: "0 x 1",
      type: "Copa selt 40+",
      data: "2026-05-14",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "45",
      homeLogo: "/times/bahea.png",
      home: "BAE",
      awayLogo: "/times/the_best.png",
      away: "TBT",
      score: "4 x 0",
      type: "Copa selt livre",
      data: "2026-05-12",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "46",
      homeLogo: "/times/novacampinas.png",
      home: "NCF",
      awayLogo: "/times/aliancafc.png",
      away: "AFC",
      score: "11 x 0",
      type: "Copa selt livre",
      data: "2026-05-12",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "47",
      homeLogo: "/times/meninos_da_vila.png",
      home: "MDV",
      awayLogo: "/times/borussia.png",
      away: "BVB",
      score: "5 x 1",
      type: "Copa selt livre",
      data: "2026-05-12",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "48",
      homeLogo: "/times/aguias_de_Deus.png",
      home: "ADF",
      awayLogo: "/times/conexaofc.png",
      away: "CFC",
      score: "7 x  3",
      type: "Copa selt livre",
      data: "2026-05-12",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "49",
      homeLogo: "/times/falcoes.png",
      home: "FAC",
      awayLogo: "/times/promi_informatica.png",
      away: "PRO",
      score: "6 x 1",
      type: "Copa selt livre",
      data: "2026-05-12",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "50",
      homeLogo: "/times/realcentral.png",
      home: "RCF",
      awayLogo: "/times/os_paraibas.png",
      away: "PRB",
      score: "2 x 8",
      type: "Copa selt livre",
      data: "2026-05-12",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "51",
      homeLogo: "/times/napoli.png",
      home: "NAP",
      awayLogo: "/times/leoesfc.png",
      away: "LEO",
      score: "4 x 2",
      type: "Copa selt livre",
      data: "2026-05-14",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "52",
      homeLogo: "/times/mec.png",
      home: "MEC",
      awayLogo: "/times/unidos_sao_joao.png",
      away: "USJ",
      score: "4 x 1",
      type: "Copa selt livre",
      data: "2026-05-14",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "53",
      homeLogo: "/times/renukaadc.png",
      home: "ADC",
      awayLogo: "/times/bfc.png",
      away: "BFC",
      score: "2 x 0",
      type: "Copa selt livre",
      data: "2026-05-16",
      hora: "17:15",
      local: "Estádio verano Piromalli"
    },
    {
        id: "54",
      homeLogo: "/times/realcentral.png",
      home: "RCF",
      awayLogo: "/times/falcoes.png",
      away: "FAL",
      score: "0 x 20",
      type: "Copa selt livre",
      data: "2026-05-16",
      hora: "17:15",
      local: "Estádio verano Piromalli"
    },
    {
        id: "55",
      homeLogo: "/times/unidos_sao_joao.png",
      home: "SJC",
      awayLogo: "/times/bengala.png",
      away: "BGA",
      score: "4 x 2",
      type: "Copa selt livre",
      data: "2026-05-16",
      hora: "18:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "56",
      homeLogo: "/times/aguias_de_Deus.png",
      home: "ADF",
      awayLogo: "/times/meninos_da_vila.png",
      away: "MDV",
      score: "4 x 5",
      type: "Copa selt livre",
      data: "2026-05-16",
      hora: "18:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "57",
      homeLogo: "/times/novacampinas.png",
      home: "NCF",
      awayLogo: "/times/bahea.png",
      away: "BAE",
      score: "0 x 3",
      type: "Copa selt livre",
      data: "2026-05-16",
      hora: "19:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "58",
      homeLogo: "/times/point.png",
      home: "PIT",
      awayLogo: "/times/becofc.png",
      away: "BEC",
      score: "3 x 4",
      type: "Copa selt livre",
      data: "2026-05-16",
      hora: "19:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "59",
      homeLogo: "/times/amigos_do_futebol40.png",
      home: "ADF",
      awayLogo: "/times/arenamartinez50.png",
      away: "AMB",
      score: "1 x 1",
      type: "Copa selt 50+",
      data: "2026-05-19",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "60",
      homeLogo: "/times/assentamento50.png",
      home: "ASS",
      awayLogo: "/times/bengala.png",
      away: "BGA",
      score: "0 x 4",
      type: "Copa selt 50+",
      data: "2026-05-19",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "61",
      homeLogo: "/times/mec.png",
      home: "MEC",
      awayLogo: "/times/napoli.png",
      away: "NAP",
      score: "4 x 3",
      type: "Copa selt livre",
      data: "2026-05-19",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "62",
      homeLogo: "/times/bemamigosfc.png",
      home: "BAG",
      awayLogo: "/times/mec.png",
      away: "MEC",
      score: "0 x 3",
      type: "Copa selt 40+",
      data: "2026-05-19",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "63",
      homeLogo: "/times/bahea.png",
      home: "BAE",
      awayLogo: "/times/falcoes.png",
      away: "FAC",
      score: "0 x 4",
      type: "Copa selt 40+",
      data: "2026-05-19",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "64",
      homeLogo: "/times/athleticfc.png",
      home: "ATL",
      awayLogo: "/times/guerreirosfc.png",
      away: "GFC",
      score: "2 x 2",
      type: "Copa selt livre",
      data: "2026-05-19",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "65",
      homeLogo: "/times/becofc.png",
      home: "BEC",
      awayLogo: "/times/the_best.png",
      away: "TBT",
    score: "2 x 1",
      type: "Copa selt livre",
      data: "2026-05-21",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "66",
      homeLogo: "/times/aliancafc.png",
      home: "AFC",
      awayLogo: "/times/point.png",
      away: "PIT",
      score: "1 x 15",
      type: "Copa selt livre",
      data: "2026-05-21",
      hora: "21:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "67",
      homeLogo: "/times/bengala.png",
      home: "BGA",
      awayLogo: "/times/borussia.png",
      away: "BVB",
      score: "4 x 4",
      type: "Copa selt livre",
      data: "2026-05-21",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "68",
      homeLogo: "/times/conexaofc.png",
      home: "CFC",
      awayLogo: "/times/saojose.png",
      away: "SJC",
      score: "0 x 10",
      type: "Copa selt livre",
      data: "2026-05-21",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "69",
      homeLogo: "/times/bfc.png",
      home: "BFC",
      awayLogo: "/times/promi_informatica.png",
      away: "PRO",
      score: "3 x 0",
      type: "Copa selt livre",
      data: "2026-05-21",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "70",
      homeLogo: "/times/os_paraibas.png",
      home: "PRB",
      awayLogo: "/times/renukaadc.png",
      away: "ADC",
      score: "6 x 1",
      type: "Copa selt livre",
      data: "2026-05-21",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "71",
      homeLogo: "/times/guerreirosfc.png",
      home: "GFC",
      awayLogo: "/times/leoesfc.png",
      away: "LEO",
      score: "6 x 1",
      type: "Copa selt livre",
      data: "2026-05-23",
      hora: "17:15",
      local: "Estádio verano Piromalli"
    },
    {
        id: "72",
      homeLogo: "/times/unidos_sao_joao.png",
      home: "USJ",
      awayLogo: "/times/athleticfc.png",
      away: "ATL",
      score: "0 x 2",
      type: "Copa selt livre",
      data: "2026-05-23",
      hora: "17:15",
      local: "Estádio verano Piromalli"
    },
    {
        id: "73",
      homeLogo: "/times/falcoes.png",
      home: "FAL",
      awayLogo: "/times/promi_informatica.png",
      away: "PRO",
      score: "3 x 1",
      type: "Copa selt 40+ (quartas)",
      data: "2026-05-23",
      hora: "18:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "74",
      homeLogo: "/times/bahea.png",
      home: "BAE",
      awayLogo: "/times/grupodeubom.png",
      away: "GBD",
      score: "0 x 3",
      type: "Copa selt 40+ (quartas)",
      data: "2026-05-23",
      hora: "18:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "75",
      homeLogo: "/times/bengala.png",
      home: "BAG",
      awayLogo: "/times/amigos_do_futebol40.png",
      away: "ADF",
      score: "5 x 4",
      type: "Copa selt 40+ (quartas)",
      data: "2026-05-23",
      hora: "19:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "76",
      homeLogo: "/times/mec.png",
      home: "MEC",
      awayLogo: "/times/assentamento50.png",
      away: "ASS",
      score: "0 x 8",
      type: "Copa selt 40+ (quartas)",
      data: "2026-05-23",
      hora: "19:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "77",
      homeLogo: "/times/point.png",
      home: "PIT",
      awayLogo: "/times/os_paraibas.png",
      away: "PRB",
      score: "7 x 5",
      type: "Copa ADC",
      data: "2026-05-24",
      hora: "08:00",
      local: "Arena ADC"
    },
    {
        id: "78",
      homeLogo: "/times/nova_alianca.png",
      home: "NAL",
      awayLogo: "/times/boleirosfc.png",
      away: "BLS",
      score: "5 x 1",
      type: "Copa ADC",
      data: "2026-05-24",
      hora: "09:10",
      local: "Arena ADC"
    },
    {
        id: "79",
      homeLogo: "/times/sporting-guaicarafc.png",
      home: "SGC",
      awayLogo: "/times/raizesportiva.png",
      away: "RZS",
      score: "13 x 0",
      type: "Copa ADC",
      data: "2026-05-24",
      hora: "08:00",
      local: "Arena ADC"
    },
    {
        id: "80",
      homeLogo: "/times/the_best.png",
      home: "TBT",
      awayLogo: "/times/magos.png",
      away: "MAG",
      score: "1 x 2",
      type: "Copa ADC",
      data: "2026-05-24",
      hora: "09:10",
      local: "Arena ADC"
    },
    {
        id: "81",
      homeLogo: "/times/napoli.png",
      home: "NAP",
      awayLogo: "/times/guerreirosfc.png",
      away: "GFC",
      score: "3 x 4",
      type: "Copa selt livre",
      data: "2026-05-28",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "82",
      homeLogo: "/times/athleticfc.png",
      home: "ATL",
      awayLogo: "/times/mec.png",
      away: "MEC",
      score: "3 x 0",
      type: "Copa selt livre",
      data: "2026-05-28",
      hora: "19:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "83",
      homeLogo: "/times/leoesfc.png",
      home: "LEO",
      awayLogo: "/times/unidos_sao_joao.png",
      away: "USJ",
      score: "3 x 3",
      type: "Copa selt livre",
      data: "2026-05-30",
      hora: "18:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "84",
      homeLogo: "/times/the_best.png",
      home: "TBT",
      awayLogo: "/times/aliancafc.png",
      away: "AFC",
      score: "6 x 1",
      type: "Copa selt livre",
      data: "2026-05-30",
      hora: "17:15",
      local: "Estádio verano Piromalli"
    },
    {
        id: "85",
      homeLogo: "/times/borussia.png",
      home: "BVB",
      awayLogo: "/times/conexaofc.png",
      away: "CFC",
      score: "10 x 1",
      type: "Copa selt livre",
      data: "2026-05-30",
      hora: "18:30",
      local: "Estádio verano Piromalli"
    },
    {
        id: "86",
      homeLogo: "/times/promi_informatica.png",
      home: "PRO",
      awayLogo: "/times/os_paraibas.png",
      away: "PRB",
      score: "5 x 6",
      type: "Copa selt livre",
      data: "2026-05-30",
      hora: "17:15",
      local: "Estádio verano Piromalli"
    },
    {
        id: "87",
      homeLogo: "/times/saojose.png",
      home: "SJC",
      awayLogo: "/times/renukaadc.png",
      away: "ADC",
      score:null,
      type: "Copa selt livre - oitavas de final",
      data: "2026-06-09",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "88",
      homeLogo: "/times/mec.png",
      home: "MEC",
      awayLogo: "/times/borussia.png",
      away: "BVB",
      score: null,
      type: "Copa selt livre - oitavas de final",
      data: "2026-06-09",
      hora: "20:00",
      local: "Estádio verano Piromalli"
    },
    {
        id: "89",
      homeLogo: "/times/napoli.png",
      home: "NPI",
      awayLogo: "/times/os_paraibas.png",
      away: "PRB",
      score: null,
      type: "Copa ADC - semifinal",
      data: "2026-06-07",
      hora: "08:00",
      local: "Arena ADC"
    },
    {
        id: "90",
      homeLogo: "/times/casinhafc.png",
      home: "CFC",
      awayLogo: "/times/magos.png",
      away: "MAG",
      score: null,
      type: "Copa ADC - semifinal",
      data: "2026-06-07",
      hora: "08:00",
      local: "Arena ADC"
    },
      

    /**
     {
        id: "15",
      homeLogo: "/times/amigos_da_bola.png",
      home: "Amigos da bola",
      awayLogo: "/times/amigos_do_futebol40.png",
      away: "Amigos do Futebol",
      score: "6 x 1",
      type: "Amistoso",
      data: "2026-04-12",
      hora: "08:15",
      local: "Arena Caju"
    },
    {
        id: "16",
      homeLogo: "/times/juventus.png",
      home: "Juventus",
      awayLogo: "/times/claudineimotos.png",
      away: "Claudinei Motos",
      score: "4 x 6",
      type: "Amistoso",
      data: "2026-04-11",
      hora: "16:00",
      local: "Arena Del Rey"
    },
    {
        id: "17",
      homeLogo: "/times/bemamigosfc.png",
      home: "Bem Amigos",
      awayLogo: "/times/mec.png",
      away: "MEC",
      score: "4 x 8",
      type: "Amistoso",
      data: "2026-04-04",
      hora: "16:30",
      local: "Arena ADC"
    },
    {
        id: "18",
      homeLogo: "/times/meninos_da_vila.png",
      home: "meninos da vila",
      awayLogo: "/times/aguias_de_Deus.png",
      away: "Águias de Deus",
      score: "7 x 4",
      type: "Amistoso",
      data: "2026-04-05",
      hora: "08:30",
      local: "Arena ADC"
    },
    {
        id: "19",
      homeLogo: "/times/renukaadc.png",
      home: "Renuka ADC",
      awayLogo: "/times/ousadiafc.png",
      away: "Ousadia",
      score: "2 x 8",
      type: "Amistoso",
      data: "2026-04-05",
      hora: "08:30",
      local: "Arena ADC"
    },
    {
        id: "20",
      homeLogo: "/times/the_best.png",
      home: "The best",
      awayLogo: "/times/quebrada_fc.png",
      away: "Quebrada FC",
      score: "9 x 7",
      type: "Amistoso",
      data: "2026-04-05",
      hora: "08:00",
      local: "Golden Ball - Guaiçara"
    },
    {
        id: "21",
      homeLogo: "/times/amigosdavila.png",
      home: "Amigos da Vila",
      awayLogo: "/times/cruzeirodosalla.png",
      away: "Cruzeiro do Salla",
      score: "15 x 6",
      type: "Amistoso",
      data: "2026-04-04",
      hora: "16:00",
      local: "Centro de lazer(barbosa)"
    },
    {
        id: "22",
      homeLogo: "/times/amigos_da_bola.png",
      home: "Amigos da bola",
      awayLogo: "/times/falcoes.png",
      away: "Falcões",
      score: "4 x 3",
      type: "Amistoso",
      data: "2026-03-29",
      hora: "08:15",
      local: "Chacara do Danilo"
    },
    {
        id: "23",
      homeLogo: "/times/renukaadc.png",
      home: "Renuka ADC",
      awayLogo: "/times/mec.png",
      away: "MEC",
      score: "2 x 2",
      type: "Amistoso",
      data: "2026-03-29",
      hora: "08:30",
      local: "Arena ADC"
    },
    {
        id: "24",
      homeLogo: "/times/the_best.png",
      home: "The Best",
      awayLogo: "/times/aguias_de_Deus.png",
      away: "Águias de Deus",
      score: "4 x 2",
      type: "Amistoso",
      data: "2026-03-29",
      hora: "08:30",
      local: "Arena ADC"
    },
    {
        id: "25",
      homeLogo: "/times/magos.png",
      home: "Magos",
      awayLogo: "/times/sporting-guaicarafc.png",
      away: "Sporting Guaicara",
      score: "3 x 3",
      type: "Amistoso",
      data: "2026-03-28",
      hora: "16:00",
      local: "Arena ADC"
    },
    {
        id: "26",
      homeLogo: "/times/unidosanchieta.png",
      home: "Unidos Anchieta",
      awayLogo: "/times/juventudefc.png",
      away: "Juventude FC",
      score: "4 x 5",
      type: "Amistoso",
      data: "2026-03-28",
      hora: "09:30",
      local: "Campo Santa Rita"
    },
    {
        id: "27",
      homeLogo: "/times/amigos_da_bola.png",
      home: "Amigos da bola",
      awayLogo: "/times/bahea.png",
      away: "Bahea",
      score: "10 x 3",
      type: "Amistoso",
      data: "2026-03-22",
      hora: "08:30",
      local: "Avanhandava"
    },
    {
        id: "28",
      homeLogo: "/times/renukaadc.png",
      home: "Renuka ADC",
      awayLogo: "/times/meninos_da_vila.png",
      away: "Meninos da Vila",
      score: "3 x 5",
      type: "Amistoso",
      data: "2026-03-22",
      hora: "08:30",
      local: "Arena ADC"
    },
    {
        id: "29",
      homeLogo: "/times/bengala.png",
      home: "Bengala",
      awayLogo: "/times/the_best.png",
      away: "the best",
      score: "3 x 5",
      type: "Amistoso",
      data: "2026-03-15",
      hora: "08:30",
      local: "Promissão"
    },
    {
        id: "30",
      homeLogo: "/times/renukaadc.png",
      home: "Renuka ADC",
      awayLogo: "/times/bulldogs.png",
      away: "Bulldogs",
      score: "9 x 3",
      type: "Amistoso",
      data: "2026-03-15",
      hora: "08:30",
      local: "Arena ADC"
    },
    {
        id: "31",
      homeLogo: "/times/renukaadc.png",
      home: "Renuka ADC",
      awayLogo: "/times/the_best.png",
      away: "The best",
      score: "5 x 2",
      type: "Amistoso",
      data: "2026-03-08",
      hora: "08:30",
      local: "Arena ADC"
    }
     */
]

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const tipo = searchParams.get("tipo")

  const agora = new Date()

  const parseDate = (j: any) =>
    new Date(`${j.data}T${j.hora || "00:00"}`)

  let resultado = jogos

  if (tipo === "futuros") {
    resultado = jogos.filter(j => parseDate(j) > agora)
  }

  if (tipo === "passados") {
    resultado = jogos.filter(j => parseDate(j) <= agora)
  }

  // 🔥 NOVO: só finalizados + ordena + pega 10
  if (tipo === "passados") {
    resultado = resultado
      .filter(j => j.score) // só quem tem placar
      .sort((a, b) => parseDate(b).getTime() - parseDate(a).getTime())
      .slice(0, 10)
  }

  return NextResponse.json(resultado)
}